// Auto-generated by scripts/sync-weeks.mjs on 2025-11-23T16:01:31.981Z
// Do not edit manually.

export type WeekSourceFile = {
  name: string;
  path: string;
  language: string;
};

export type WeekMeta = {
  id: string;
  title: string;
  path: string;
  summary: string;
  sources: WeekSourceFile[];
};

export const weeks: WeekMeta[] = [
  {
    "id": "Week1",
    "title": "1주차: Modern C++ 워밍업 및 환경 적응",
    "path": "/weeks/Week1.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_smart_pointers.cpp",
        "path": "/code/Week1/01_smart_pointers.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_lambdas.cpp",
        "path": "/code/Week1/02_lambdas.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_jthread.cpp",
        "path": "/code/Week1/03_jthread.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week2",
    "title": "2주차: 쓰레드 관리 (Thread Management)",
    "path": "/weeks/Week2.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_thread_lifecycle.cpp",
        "path": "/code/Week2/01_thread_lifecycle.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_argument_passing.cpp",
        "path": "/code/Week2/02_argument_passing.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_parallel_sum.cpp",
        "path": "/code/Week2/03_parallel_sum.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week3",
    "title": "3주차: 데이터 공유와 경쟁 조건 (Data Sharing)",
    "path": "/weeks/Week3.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_race_condition.cpp",
        "path": "/code/Week3/01_race_condition.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_mutex_guard.cpp",
        "path": "/code/Week3/02_mutex_guard.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_thread_safe_list.cpp",
        "path": "/code/Week3/03_thread_safe_list.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week4",
    "title": "4주차: 교착 상태 (Deadlock)와 해결책",
    "path": "/weeks/Week4.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_deadlock_demo.cpp",
        "path": "/code/Week4/01_deadlock_demo.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_scoped_lock.cpp",
        "path": "/code/Week4/02_scoped_lock.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_dining_philosophers.cpp",
        "path": "/code/Week4/03_dining_philosophers.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week5",
    "title": "5주차: 쓰레드 간 신호 전달 (Condition Variable)",
    "path": "/weeks/Week5.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_condition_variable.cpp",
        "path": "/code/Week5/01_condition_variable.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_producer_consumer.cpp",
        "path": "/code/Week5/02_producer_consumer.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_spurious_wakeup.cpp",
        "path": "/code/Week5/03_spurious_wakeup.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week6",
    "title": "6주차: 비동기 결과 조회 (Future, Promise, Async)",
    "path": "/weeks/Week6.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_promise_future.cpp",
        "path": "/code/Week6/01_promise_future.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_async_task.cpp",
        "path": "/code/Week6/02_async_task.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_shared_future.cpp",
        "path": "/code/Week6/03_shared_future.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week7",
    "title": "7주차: 쓰레드 풀 (Thread Pool)과 안전한 큐",
    "path": "/weeks/Week7.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_thread_safe_queue.cpp",
        "path": "/code/Week7/01_thread_safe_queue.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_simple_thread_pool.cpp",
        "path": "/code/Week7/02_simple_thread_pool.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_using_thread_pool.cpp",
        "path": "/code/Week7/03_using_thread_pool.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week8",
    "title": "8주차: 원자적 연산 (Atomics)",
    "path": "/weeks/Week8.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_atomic_counter.cpp",
        "path": "/code/Week8/01_atomic_counter.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_cas_loop.cpp",
        "path": "/code/Week8/02_cas_loop.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_spinlock.cpp",
        "path": "/code/Week8/03_spinlock.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week9",
    "title": "9주차: 메모리 모델 (Memory Model)과 Lock-free",
    "path": "/weeks/Week9.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_reordering_demo.cpp",
        "path": "/code/Week9/01_reordering_demo.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_acquire_release.cpp",
        "path": "/code/Week9/02_acquire_release.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_memory_order_demo.cpp",
        "path": "/code/Week9/02_memory_order_demo.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_atomic_fence.cpp",
        "path": "/code/Week9/03_atomic_fence.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week10",
    "title": "10주차: [프로젝트] 고성능 멀티쓰레드 로거",
    "path": "/weeks/Week10.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_sync_logger.cpp",
        "path": "/code/Week10/01_sync_logger.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_async_logger.cpp",
        "path": "/code/Week10/02_async_logger.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week11",
    "title": "11주차: 네트워크 기초 (Winsock)",
    "path": "/weeks/Week11.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_winsock_init.cpp",
        "path": "/code/Week11/01_winsock_init.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_ip_address.cpp",
        "path": "/code/Week11/02_ip_address.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_simple_socket.cpp",
        "path": "/code/Week11/03_simple_socket.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week12",
    "title": "12주차: Blocking I/O와 에코 서버",
    "path": "/weeks/Week12.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_echo_server.cpp",
        "path": "/code/Week12/01_echo_server.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_echo_client.cpp",
        "path": "/code/Week12/02_echo_client.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week13",
    "title": "13주차: I/O Multiplexing (Select 모델)",
    "path": "/weeks/Week13.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_select_server.cpp",
        "path": "/code/Week13/01_select_server.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week14",
    "title": "14주차: Non-blocking I/O",
    "path": "/weeks/Week14.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_nonblocking_server.cpp",
        "path": "/code/Week14/01_nonblocking_server.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week15",
    "title": "15주차: [프로젝트] 1:N 채팅 서버 (Select 기반)",
    "path": "/weeks/Week15.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_chat_server.cpp",
        "path": "/code/Week15/01_chat_server.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week16",
    "title": "16주차: 중간 점검 및 리팩토링",
    "path": "/weeks/Week16.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_refactored_server.cpp",
        "path": "/code/Week16/01_refactored_server.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week17",
    "title": "17주차: 패킷 직렬화 (Serialization) 설계",
    "path": "/weeks/Week17.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_packet_structure.cpp",
        "path": "/code/Week17/01_packet_structure.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_serialization.cpp",
        "path": "/code/Week17/02_serialization.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week18",
    "title": "18주차: 데이터베이스 연동 기초",
    "path": "/weeks/Week18.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_mock_db.cpp",
        "path": "/code/Week18/01_mock_db.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week19",
    "title": "19주차: 세션 관리 (Session Management)",
    "path": "/weeks/Week19.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_session_manager.cpp",
        "path": "/code/Week19/01_session_manager.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week20",
    "title": "20주차: 멀티쓰레드 서버 아키텍처",
    "path": "/weeks/Week20.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_worker_pattern.cpp",
        "path": "/code/Week20/01_worker_pattern.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week21",
    "title": "21주차: Windows IOCP (I/O Completion Port) 이론",
    "path": "/weeks/Week21.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_iocp_basic.cpp",
        "path": "/code/Week21/01_iocp_basic.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week22",
    "title": "22주차: IOCP 에코 서버 구현",
    "path": "/weeks/Week22.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_iocp_echo.cpp",
        "path": "/code/Week22/01_iocp_echo.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_iocp_pitfalls.cpp",
        "path": "/code/Week22/02_iocp_pitfalls.cpp",
        "language": "cpp"
      },
      {
        "name": "src/03_iocp_raii.cpp",
        "path": "/code/Week22/03_iocp_raii.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week23",
    "title": "23주차: IOCP 채팅 서버 (기본)",
    "path": "/weeks/Week23.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_iocp_chat_basic.cpp",
        "path": "/code/Week23/01_iocp_chat_basic.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week24",
    "title": "24주차: IOCP 채팅 서버 (심화)",
    "path": "/weeks/Week24.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_ring_buffer.cpp",
        "path": "/code/Week24/01_ring_buffer.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_packet_handling.cpp",
        "path": "/code/Week24/02_packet_handling.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week25",
    "title": "25주차: Boost.Asio (Standalone) 기초",
    "path": "/weeks/Week25.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_timer_sync.cpp",
        "path": "/code/Week25/01_timer_sync.cpp",
        "language": "cpp"
      },
      {
        "name": "src/02_timer_async.cpp",
        "path": "/code/Week25/02_timer_async.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week26",
    "title": "26주차: Asio 에코 서버",
    "path": "/weeks/Week26.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_asio_echo.cpp",
        "path": "/code/Week26/01_asio_echo.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week27",
    "title": "27주차: Asio 채팅 서버",
    "path": "/weeks/Week27.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_asio_chat.cpp",
        "path": "/code/Week27/01_asio_chat.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week28",
    "title": "28주차: 성능 프로파일링",
    "path": "/weeks/Week28.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/01_slow_server.cpp",
        "path": "/code/Week28/01_slow_server.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week29",
    "title": "29주차: [Final] 종합 프로젝트 - 아키텍처 설계",
    "path": "/weeks/Week29.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/main.cpp",
        "path": "/code/Week29/main.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week30",
    "title": "30주차: [Final] 코어 서버 (ServerCore) 구현",
    "path": "/weeks/Week30.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/main.cpp",
        "path": "/code/Week30/main.cpp",
        "language": "cpp"
      },
      {
        "name": "src/ServerCore.h",
        "path": "/code/Week30/ServerCore.h",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week31",
    "title": "31주차: [Final] 게임 로직 (GameServer) 구현",
    "path": "/weeks/Week31.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/main.cpp",
        "path": "/code/Week31/main.cpp",
        "language": "cpp"
      }
    ]
  },
  {
    "id": "Week32",
    "title": "32주차: [Final] 최종 안정화 및 부하 테스트",
    "path": "/weeks/Week32.md",
    "summary": "요약 정보가 없습니다.",
    "sources": [
      {
        "name": "src/main.cpp",
        "path": "/code/Week32/main.cpp",
        "language": "cpp"
      }
    ]
  }
];
